config/routes.rb
Rails.application.routes.draw do
  get 'ui(/:action)', controller: 'ui'

  root to: 'pages#index'
  get '/help', to: 'pages#help'
  resources :users, only: [:show, :new, :create]
  resources :packs, only: [:show, :create]
  resources :cards, only: [:new, :create, :show]
  get '/answer/:card_id', to: 'cards#answer', as: :answer
  get '/learned/:card_id', to: 'cards#learned', as: :learned
  get '/random_card', to: 'cards#random_card', as: :random_card

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :pack
  validates_presence_of :front, :back
  validates_numericality_of :attempts, greater_than: -1
  validates_format_of :learning_stage, with: /(unfamiliar)|(familiar)|(learned)/

  def creation_date
    time = self.created_at.time
    time.month.to_s + "-" + time.day.to_s + "-" + time.year.to_s
  end
end

app/models/pack.rb
class Pack < ActiveRecord::Base
  belongs_to :user
  has_many :cards
  validates_presence_of :name

  def unlearned_cards
    self.cards.map.select { |c| c if c.learning_stage != "learned" }
  end

  def gdata
    result = [['Card', 'Attempts']]
    self.cards.each do |card|
      result << [card.front, card.attempts]
    end
    result
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :packs
  validates_presence_of :username, :email
  validates_uniqueness_of :email
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def new
    @pack_id = params[:data][:pack_id]
    @pack = Pack.find(params[:data][:pack_id])
    @card = Card.new
  end

  def create
    @card = Card.new(card_params)
    Pack.find(params[:pack_id]).cards << @card
    if @card.save
      redirect_to user_path(current_user)
    else
      flash[:error] = "Something went wrong."
      render :new
    end
  end

  def random_card
    pack = Pack.find(params[:data][:pack_id])
    if pack.cards.empty?
      flash[:error] = "There are no cards in that pack. You can create some with the Add Cards link below."
      redirect_to pack_path(params[:data][:pack_id])
    elsif pack.unlearned_cards.empty?
      flash[:success] = "You have learned all the cards in the #{pack.name} deck. Congratulations! You will be notified when you should review them again. Maybe you have other decks to review?"
    #redirect_to pack_path(params[:data][:pack_id])
      redirect_to user_path(current_user)
    else
      redirect_to card_path(pack.unlearned_cards.sample.id)
    end
  end

  def show
    @card = Card.find(params[:id])
    @card.update!(attempts: @card.attempts + 1)
  end

  def answer
    @card = Card.find(params[:card_id])
  end

  def learned
    @card = Card.find(params[:card_id])
    @card.update!(learning_stage: 'learned')
  end

  private

  def card_params
    params.require(:card).permit(:front, :back)
  end
end

app/controllers/packs_controller.rb
class PacksController < ApplicationController
  def show
    @pack = Pack.find(params[:id])
    @chart_data = [["Card", "Attempts",]]
    @chart_data += @pack.cards.map { |card| [card.front, card.attempts] }
  end

  def create
    pack = Pack.new(pack_params)
    pack.percent_learned = 0
    if pack.save
      current_user.packs << pack
      redirect_to user_path(current_user)
    else
      flash[:error] = "Something went wrong there. Try again."
      redirect_to user_path(current_user)
    end
  end

  private

  def pack_params
    params.require(:pack).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @user = User.new
  end

  def help
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by email: params[:email]
    if user && user.authenticate(params[:password])
      flash[:success] = "Welcome back, #{user.username}"
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash[:error] = "Username or password not recognized."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/ui_controller.rb
class UiController < ApplicationController
  def front
  end

  def register
  end

  def user_index
  end

  def pack_page
  end

  def new_card
  end

  def card_front
  end

  def card_back
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      flash[:success] = "Welcome, #{@user.username}"
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    @pack = Pack.new
    @user = current_user
    update_user_progress(@user)
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def update_user_progress(user)
    packs = user.packs
    if not packs.empty?
      packs.each do |pack|
        learned = pack.cards.where('learning_stage = ?', 'learned').count
        percentage = ((learned / (pack.cards.count * 1.0)) * 100).round(2)
        percentage.to_s.to_i
        pack.update!(percent_learned: percentage)
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/answer.html.haml
%a.button.small{:href => user_path(current_user)} I'm done reviewing
%center
  %h1.text-center{ :style => "margin-top: 190px" } #{@card.front}
  %h1.text-center{ :style => "margin-top: 190px" } #{@card.back}

  %a.button{:style => "margin-top: 200px", :href => random_card_path(:data => {:pack_id => @card.pack_id})} Next

app/views/cards/learned.html.haml
%a.button.small{:href => user_path(current_user)} I'm done reviewing
%center
  %h1.text-center{ :style => "margin-top: 190px" } #{@card.front}
  %h1.text-center #{@card.back}
  %p Congratulations! This card will be marked as learned.

  %a.button{:style => "margin-top: 200px", :href => random_card_path(:data => {:pack_id => @card.pack_id})} Next

app/views/cards/new.html.haml
%br
%h2.text-center #{@pack.name}
%hr

%br
%br
%br
= form_for @card do |f|
  = hidden_field_tag "pack_id", @pack_id
  .row
    .small-9.columns
      .row
        .small-3.columns
        .small-9.columns
          = f.text_field :front, placeholder: 'Card Front'
  .row
    .small-9.columns
      .row
        .small-3.columns
        .small-9.columns
          = f.text_area :back, placeholder: 'Card Back', rows: 10
          = f.submit "Submit", class: 'button small radius'

app/views/cards/show.html.haml
%a.button.small{:href => user_path(current_user)} I'm done reviewing
%center
  %h1.text-center{ :style => "margin-top: 190px" } #{@card.front}
  %h1.text-center.hide{ :style => "margin-top: 190px" } Marketplace

  .hide
    %a.button.center{:style => "margin-top: 200px", :href => random_card_path(:data => {:pack_id => @card.pack_id})} Next


  .row
    .large-10.columns.large-offset-1
      %ul.button-group{ :style => "margin-top: 200px" }
        %li
          %a.button{:style => "margin-right: 200px", :href => learned_path(@card.id), :data => {:pack_id => @card.pack_id}} I know it!
        %li
          %a.button{:style => "margin-right: 200px", :href => answer_path(@card.id), :data => {:pack_id => @card.pack_id}} Sorta (1)
        %li
          %a.button{:href => answer_path(@card.id), :data => {:pack_id => @card.pack_id}} No clue (3)

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "en"}
  %head
    %title Memboost
    %meta{ :charset => "utf-8" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    %title= content_for?(:title) ? yield(:title) : "Untitled"

    = stylesheet_link_tag "application"
    = javascript_include_tag "vendor/modernizr"
    = yield :head
    = csrf_meta_tag



  %body
    %nav
      = render 'shared/navigation'
    %section.content.clearfix
      = render 'shared/messages'
      = yield
      = javascript_include_tag "application"

app/views/packs/show.html.haml
- content_for :head do
  %script{:src => "https://www.google.com/jsapi", :type => "text/javascript"}
  :javascript
    google.load("visualization", "1", {packages:["corechart"]});
    google.setOnLoadCallback(drawChart);
    function drawChart() {
    var data = google.visualization.arrayToDataTable(
    #{@chart_data}
    );
    var options = {
    title: 'Attempts per card',
    legend: { position: 'none' },
    histogram: { bucketSize: 2 }
    };

    var chart = new google.visualization.Histogram(document.getElementById('chart_div'));
    chart.draw(data, options);
    }

%br
%h2.text-center #{@pack.name} (#{@pack.cards.count})
%hr
.row
  .div.small-2.columns
    %ul.side-nav
      %li
        %h5
          = link_to "Review", random_card_path(data: { pack_id: @pack.id })
      %li
        %h5
          = link_to "Add Cards", new_card_path(data: { pack_id: @pack.id })
      %li
        %h5
          = link_to "All Decks", user_path(current_user)
  .div.small-10.columns
    %dl.tabs{"data-tab" => ""}
      %dd.active
        %a{:href => "#panel1"} Cards
      %dd
        %a{:href => "#panel2"} Learning Rate
      %dd
        %a{:href => "#panel3"} Tab 3
      %dd
        %a{:href => "#panel4"} Tab 4
    .tabs-content
      #panel1.content.active
        %table
          %thead
            %tr
              %th{:width => "200"} Prompt
              %th{:width => "350"} Answer
              %th{:width => "15"} Attempts
              %th{:width => "100"} Added
              %th{:width => "100"} Learned
          %body
            - @pack.cards.each do |card|
              %tr
                %td #{card.front}
                %td #{card.back}
                %td #{card.attempts}
                %td #{card.creation_date}
                %td ?
      #panel2.content
        #chart_div{:style => "width: 500px; height: 400px;"}
      #panel3.content
        %p This is the third panel of the basic tab example. This is the third panel of the basic tab example.
      #panel4.content
        %p This is the fourth panel of the basic tab example. This is the fourth panel of the basic tab example.

app/views/pages/help.html.haml
%h2 Help Page: Under Construction

app/views/pages/index.html.haml
%br
%h1.text-center Memboost

.row
  .large-12.columns
    %p

      Memboost is a spaced repetition learning program. Enter any item
      you wish to memorize into the program &mdash; a vocabulary word, for
      instance &mdash; and Memboost will help you to learn it quickly and
      retain it indefinitely.

    %p

      The principle is simple but powerful. Once an item has been
      learned, all that's necessary to remember it indefinitely is
      periodic reinforcement. Memboost will check your retention of a
      given item to gauge whether it needs more or less frequent
      reinforcement, and it will reschedule that item for a future
      date depending on how well you've retained it.

    %p

      Memboost takes the pain out of studying large quantities of
      information --- once an item is entered into the system,
      everything else is taken care of. All you need to do is review
      it on a regular basis.

      %br
  %ul.inline-list.right
    %li
      %a.button.small.radius{:href => login_path, :class => "right"} Login
      %li
        %a.button.small.radius{:href => new_user_path, :class => "right"} Register

app/views/shared/_error_messages.html.haml
- if @user.errors.any?
  %ul.error
    - @user.errors.full_messages.each do |msg|
      %li= msg

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  - if name == 'alert'
    .alert-box.alert{"data-alert" => ""}
      #{msg}
      %a.close{:href => "#"} &times;
  - else
    .alert-box.success{"data-alert" => ""}
      #{msg}
      %a.close{:href => "#"} &times;

app/views/shared/_navigation.html.haml
%nav.top-bar{"data-topbar" => "", :role => "navigation"}
  %ul.title-area
    %li.name
      %h1
        - if current_user
          %a{:href => user_path(current_user.id)} #{current_user.username}@Memboost
        - else
          %a{:href => root_path} Memboost
        - if current_user
          %section.top-bar-section
            / Right Nav Section
            %ul.right
              %li
                %a{:href => user_path(current_user)} Your Packs
              %li
                %a{:href => help_path} Help
              %li
                %a{:href => logout_path} Log out
        - else
          %section.top-bar-section
            %ul.right
              %li
                %a{:href => help_path} Help

app/views/ui/card_back.html.haml
%center
  %h1.text-center{ :style => "margin-top: 200px" } Marketplace

  %a.button{:style => "margin-top: 200px", :href => "#"} Next

app/views/ui/front.html.haml
%h1.text-center Memboost
%hr
.row
  .large-8.columns.large-offset-2
    %p
      - 50.times do
        Lorem Ipsum
%br
%br
.row
  .large-5.columns.large-offset-3
    %fieldset
      %legend Log in
      %input{ :placeholder => "yourname@yourmail.com", :type => "text" }
      %input{ :placeholder => "your password", :type => "text" }
      %a.button.small{:class => "[ radius round ]", :href => "#", :role => "button"} Submit
      %a.right{ :href => "#" } Register

app/views/ui/new_card.html.haml
%br
%h2.text-center Greek Vocabulary
%hr

%br
%br
%br
%form
  .row
    .small-9.columns
      .row
        .small-3.columns
          %label.right.inline{:for => "right-label"} Side 1:
        .small-9.columns
          %input#right-label{:placeholder => "", :type => "text"}
  .row
    .small-9.columns
      .row
        .small-3.columns
          %label.right.inline{:for => "right-label"} Side 2:
        .small-9.columns
          %input#right-label{:placeholder => "", :type => "text"}
            %a.button.small.radius{ :href => "#", :role => "button"} Save New Card

app/views/ui/pack_page.html.haml
%br
%h2.text-center Greek Vocabulary
%hr
%ul.side-nav
  %li
    %h3
      %a{ :href => "#" } Begin review
  %li
    %h3
      %a{ :href => "#" } Add Cards
  %li
    %h3
      %a{ :href => "#" } Settings

app/views/ui/register.html.haml
%h1.text-center Memboost

.row
  .large-8.columns.large-offset-2
    %p Create an account and begin training your memory.

%br
%br
.row
  .large-5.columns.large-offset-3
    %fieldset
      %legend Register
      %input{ :placeholder => "User Name", :type => "text" }
      %input{ :placeholder => "yourname@yourmail.com", :type => "text" }
      %input{ :placeholder => "your password", :type => "text" }
      %a.button.small{:class => "[ radius round ]", :href => "#", :role => "button"} Submit

app/views/ui/user_index.html.haml
%br
%br
.row
  .large-8.columns
    %h2 Your Flashcard Packs
.row
  .large-8.columns.large-offset-1
    %h3
      %a{ :href => "#" } Ancient Greek
      .nice.round.progress.success
        %span.meter{:style => "width: 30%"}
    %h3
      %a{ :href => "#" } U.S. History
      .nice.round.progress.success
        %span.meter{:style => "width: 90%"}
    %h3
      %a{ :href => "#" } Ruby on Rails
      .nice.round.progress.success
        %span.meter{:style => "width: 10%"}

app/views/users/index.html.haml
%br
%br
.row
  .large-10.columns
    %h2 #{@user.username}'s Flashcard Packs
    %hr
.row
  .large-8.columns.large-offset-1
    - @user.packs.each do |pack|
      %h3
        %a{ :href => "#" } #{pack.name} (#{pack.cards.count} cards)
        .nice.round.progress.success
          %span.meter{:style => "width: 30%"}

app/views/users/new.html.haml
%br
.row
  .large-5.columns.large-offset-3
    %fieldset
      %legend Register
      = form_for @user do |f|
        = render 'shared/error_messages'
        = f.text_field :username, class: 'form-control', autofocus: true, placeholder: 'User Name'
        = f.text_field :email, class: 'form-control', placeholder: 'Email address'
        = f.password_field :password, class: 'form-control', placeholder: 'Password'
        = f.submit "Submit", class: 'button small radius'

app/views/users/show.html.haml
%br
.row.left
  .small-3.columns
    = form_for @pack do |f|
      = f.text_field :name, class: 'form-control left', placeholder: "New Pack Name"
      = f.submit "Create New Pack", class: 'button tiny left'
  .small-8.columns
    %h2 Flashcard Packs
    %hr
    - if @user.packs.empty?
      %h4 You have no flashcard packs, yet. You can create your first on this page.
    - else
      - @user.packs.each do |pack|
        %h3
          %a{ :href => pack_path(pack.id) } #{pack.name}
        .small-12.columns
          %a.tiny{ :href => new_card_path(data: { pack_id: pack.id })} create card -- (#{pack.cards.count} cards)
          %a.tiny.right{ :href => random_card_path(data: { pack_id: pack.id }) } review this deck
          .nice.round.progress.success
            %span.meter{:style => "width: #{pack.percent_learned}%"}